proyectofinanzas/finanzas/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('resultados/', views.Busqueda, name='Resultados'),
    path('list/<str:tipo>/', views.list, name='list'),
    path('miscortes/', views.listCorte, name='listCorte'),
    path('cortes/<int:id>/', views.listCorteDet, name='listCorteDet'),
    path('cortes/genera/', views.GeneraCorte, name='GeneraCorte'),
    path('edit/e/<int:id>/', views.updateE, name='updateE'),
    path('edit/i/<int:id>/', views.updateI, name='updateI'),
    path('edit/r/<int:id>/', views.updateR, name='updateR'),
    path('edit/p/<int:id>/', views.updateP, name='updateTI'),
    path('add/e/', views.createE, name='createE'),
    path('add/i/', views.createI, name='createI'),
    path('add/r/', views.createR, name='createR'),
    path('add/p/', views.createP, name='createP'),
	path('delete/<str:tipo>/<int:id>/', views.delete, name='delete'),
    path('logout/', views.user_logout, name='user_logout'),
    path('create', views.create, name='create'),
    path('profile', views.profile, name='profile'),
    path('profile/edit/', views.profileedit, name='editprofile'),
    path('profile/add/user', views.adduser, name='crearusuario'),
    path('profile/edit/password', views.editPassword, name='editprofilePassword'),
    path('registro/ingreso/', views.RegistroIngreso, name='RegistroIngreso'),
    path('registro/gastos/', views.RegistroGasto, name='RegistroGasto'),
    path('transacciones/', views.Transaccione, name='Transacciones'),
    path('gastos/', views.RegistroGasto, name='Gastos'),
    path('add/transacciones', views.AddTransaccione, name='AddTransaccione'),
    path('edit/transacciones/<int:id>/', views.EditTransaccione, name='EditTransaccione'),
    path('renderh/c/<int:id>/', views.Pdfp, name='GenerarHTML'),
    path('renderc/c/<int:id>/', views.Csv, name='GenerarPDF'),
    path('render/c/<int:id>/', views.Pdf.as_view()), 
]

proyectofinanzas/proyectofinanzas/urls.py
from django.contrib import admin
from django.urls import path, include
from finanzas.views import login_user

urlpatterns = [
path ("", include ('finanzas.urls')),
    path('admin/', admin.site.urls),
    path('login/',login_user,name='login'),
    path('accounts/login/',login_user,name='login'),
    
]

proyectofinanzas/finanzas/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import AbstractUser,User
from django.conf import settings
import datetime



# Create your models here.


class Users(AbstractUser):
    cedula = models.CharField(max_length=13, blank=True)
    tipoPersona = models.CharField(max_length=3, choices=(('F', 'Fisica'), ('J', 'Juridica')),default='F')
    limite = models.IntegerField(default=0)


class Egreso(models.Model):
    id = models.AutoField (primary_key=True, help_text= 'ID  de Egreso')
    Usuario=models.ForeignKey (Users, on_delete=models.CASCADE, default=1)
    TipoEgreso=models.CharField (max_length=50, help_text='Tipo de egreso')
    Descripcion= models.CharField (max_length=50, help_text='Descripcion')
    EstadoActivo=models.BooleanField (default=1)

    def __str__(self):
        return self.TipoEgreso


class RenglonEgreso (models.Model):
    id = models.AutoField (primary_key=True, help_text= 'ID Gestion de Ingreso')
    Usuario=models.ForeignKey (Users, on_delete=models.CASCADE, default=1)
    Nombre=models.CharField (max_length=50, help_text='Tipo de ingreso')
    Descripcion= models.CharField (max_length=50, help_text='Descripcion')
    Institucion=models.CharField(max_length=35, help_text='Institucion, empleador o cliente')
    EstadoActivo=models.BooleanField (default=1)

    def __str__(self):
        return self.Nombre

class TipoPago (models.Model):
    id = models.AutoField (primary_key=True, help_text= 'ID Gestion de Ingreso')
    Usuario=models.ForeignKey (Users, on_delete=models.CASCADE, default=1)
    Descripcion=models.CharField (max_length=50, help_text='Tipo de de pago (Tarjeta, efectivo, etc).')
    EstadoActivo=models.BooleanField (default=1)

    def __str__(self):
        return self.Descripcion

class Fuente (models.Model):
    id = models.AutoField (primary_key=True, help_text= 'ID Gestion de Ingreso')
    Usuario=models.ForeignKey (Users, on_delete=models.CASCADE, default=1)
    Descripcion=models.CharField (max_length=50, help_text='Fuente Ingreso')
    Institucion=models.CharField(max_length=35)
    EstadoActivo=models.BooleanField (default=1)

    def __str__(self):
        return self.Descripcion

class Ingreso (models.Model):
    id = models.AutoField (primary_key=True, help_text= 'ID de Ingreso')
    Usuario=models.ForeignKey (Users, on_delete=models.CASCADE, default=1)
    TipoIngreso=models.CharField (max_length=50, help_text='Tipo de ingreso')
    Fuente= models.ForeignKey(Fuente, on_delete=models.CASCADE)
    Descripcion= models.CharField (max_length=50, help_text='Descripcion')
    EstadoActivo=models.BooleanField (default=1)

    def __str__(self):
        return self.TipoIngreso

class GestionEgreso (models.Model):
    id = models.AutoField (primary_key=True, help_text= 'ID Gestion de Ingreso')
    Usuario=models.ForeignKey (Users, on_delete=models.CASCADE, default=1)
    TipoIngreso=models.ForeignKey (Egreso, on_delete=models.CASCADE)
    Renglon=models.ForeignKey (RenglonEgreso, on_delete=models.CASCADE)
    TipoPago=models.ForeignKey (TipoPago, on_delete=models.CASCADE)
    Descripcion= models.CharField (max_length=50, help_text='Descripcion')
    EstadoActivo=models.BooleanField (default=1)

    def __str__(self):
        return self.Descripcion


class Transacciones (models.Model):
    id = models.AutoField (primary_key=True, help_text= 'ID Transaccion')
    Usuario=models.ForeignKey (Users, on_delete=models.CASCADE, default=1)
    TipoTransaccion=models.CharField(max_length=1, choices=(('I', 'Ingreso'), ('E', 'Egreso')),default='')
    FechaTransaccion=models.DateField(default=datetime.date.today)
    FechaRegistro=models.DateField (auto_now=True)
    Monto=models.CharField (max_length=12, help_text='Monto Transaccion')
    Descripcion= models.CharField (max_length=50, help_text='Descripcion')
    EstadoActivo=models.BooleanField (default=1)

    def __str__(self):
        return self.Descripcion

class Corte (models.Model):
    id = models.AutoField (primary_key=True, help_text= 'ID Corte')
    Usuario=models.ForeignKey (Users, on_delete=models.CASCADE, default=1)
    Ano=models.IntegerField (validators=[MinValueValidator(2000)], default=2019, help_text='Ano')
    Mes=models.CharField(max_length=3, choices=(('Ene', 'Enero'), ('Feb', 'Febrero'),('Mar', 'Marzo'), ('Abr', 'Abril'),
    ('May', 'Mayo'), ('Jun', 'Junio'),('Jul', 'Julio'), ('Ago', 'Agosto'),('Sep', 'Septiembre'), ('Oct', 'Octubre'),
    ('Nov', 'Noviembre'), ('Dic', 'Diciembre')),default='')
    FechaCorte=models.DateField(auto_now=True)
    BalanceInicial=models.IntegerField (default=0)
    TotalIngresos=models.IntegerField (default=0)
    TotalEgresos=models.IntegerField (default=0)
    BalanceCorte=models.IntegerField (default=0)
    Comentario=models.TextField(default='')
    EstadoActivo=models.BooleanField (default=1)
    

    def __str__(self):
        return '{} {}'.format(self.Mes,self.id)

    
class TransaccionesCorte (models.Model):
    id = models.AutoField (primary_key=True, help_text= 'ID Transaccion')
    Usuario=models.ForeignKey (Users, on_delete=models.CASCADE, default=1)
    Transaccion = models.ForeignKey(Transacciones, on_delete=models.CASCADE, default=1)
    Activo=models.BooleanField (default=1)
    corte = models.ForeignKey (Corte,on_delete=models.CASCADE, default=0)
    fecha = models.DateField (default=datetime.date.today)

    def __str__(self):
        return self.Transaccion.Descripcion

proyectofinanzas/finanzas/views.py
from django.shortcuts import get_object_or_404, render_to_response, redirect, render, reverse,HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from .models import *
from .forms import *
from .render import *
from django.contrib.auth import authenticate, login, logout
from django.conf import settings
from datetime import datetime
import io
from django.http import FileResponse
from reportlab.pdfgen import canvas
from easy_pdf.views import PDFTemplateView
from django.views.generic import View
from django.utils import timezone
import csv
from django.db.models import Q
from itertools import chain



@login_required
def profile(request):
    data = Users.objects.get(username = request.user)
    if request.method == 'POST':
        form = EditForm(request.POST, instance=data)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('profile'))
    else:
        form = EditForm(instance=data)

    context = {'username':request.user,'form':form}
    return render(request, 'finanzas\profile.html', context)

@login_required
def profileedit(request):
    data = Users.objects.get(username = request.user)
    if request.method == 'POST':
        form = EditForm(request.POST, instance=data)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('profile'))
    else:
        form = EditForm(instance=data)

    context = {'username':request.user,'form':form}
    return render(request, 'finanzas/edit.html', context)


@login_required
def adduser(request):
    data = Users.objects.get(username = request.user)
    if request.method == 'POST':
        form = CreateForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('profile'))
    else:
        form = CreateForm()

    context = {'username':request.user,'form':form}
    return render(request, 'finanzas/edit.html', context)


@login_required
def editPassword(request):
    data = Users.objects.get(username = request.user)
    if request.method == 'POST':
        form = EditPasswordForm(request.POST, instance=data)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('profile'))
    else:
        form = EditPasswordForm(instance=data)

    context = {'username':request.user,'form':form}
    return render(request, 'finanzas/edit.html', context)



@login_required
def create(request):
    data = Users.objects.get(username = request.user)
    if request.method == 'POST':
        form = EditPasswordForm(request.POST, instance=data)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('profile'))
    else:
        form = EditPasswordForm(instance=data)

    context = {'username':request.user,'form':form}
    return render(request, 'finanzas/edits.html', context)



@login_required
def delete(request,tipo,id):

	if tipo == 'e':
		to_delete = get_object_or_404(Egreso,id=id,Usuario = request.user)
		form = DelEgresoForm(request.POST or None, instance = to_delete)
	elif tipo == 'i':
		to_delete = get_object_or_404(Ingreso,id=id,Usuario = request.user)
		form = DelIngresoForm(request.POST or None, instance = to_delete)
	elif tipo == 'r':
		to_delete = get_object_or_404(RenglonEgreso,id=id,Usuario = request.user)
		form = DelRenglonEgresoForm(request.POST or None, instance = to_delete)
	elif tipo == 'p':
		to_delete = get_object_or_404(TipoPago,id=id,Usuario = request.user)
		form = DelTipoPagoForm(request.POST or None, instance = to_delete)
	elif tipo == 't':
		to_delete = get_object_or_404(Transacciones,id=id,Usuario = request.user)
		form = DelTransaccionesForm(request.POST or None, instance = to_delete)
	elif tipo == 'c':
		to_delete = get_object_or_404(Corte,id=id,Usuario = request.user)
		form = DelCorteForm(request.POST or None, instance = to_delete)  


	if request.method == "POST":
		if tipo == 'e':
			to_delete = get_object_or_404(Egreso,id=id,Usuario = request.user)
			form = DelEgresoForm(request.POST or None, instance = to_delete)
			redirect = '/list/{}'.format(tipo)
		elif tipo == 'i':
			to_delete = get_object_or_404(Ingreso,id=id,Usuario = request.user)
			form = DelIngresoForm(request.POST or None, instance = to_delete)
			redirect = '/list/{}'.format(tipo)
		elif tipo == 'r':
			to_delete = get_object_or_404(RenglonEgreso,id=id,Usuario = request.user)
			form = DelRenglonEgresoForm(request.POST or None, instance = to_delete)
			redirect = '/list/{}'.format(tipo)
		elif tipo == 'p':
			to_delete = get_object_or_404(TipoPago,id=id,Usuario = request.user)
			form = DelTipoPagoForm(request.POST or None, instance = to_delete)
			redirect = '/list/{}'.format(tipo)
		elif tipo == 't':
			to_delete = get_object_or_404(Transacciones,id=id,Usuario = request.user)
			form = DelTransaccionesForm(request.POST or None, instance = to_delete)
			redirect = '/transacciones/'
		elif tipo == 'c':
			to_delete = get_object_or_404(Corte,id=id,Usuario = request.user)
			form = DelCorteForm(request.POST or None, instance = to_delete)
			redirect = '/miscortes/'

		if form.is_valid():
			to_delete.EstadoActivo=0
			to_delete.save()
			return HttpResponseRedirect(redirect)
		else:
			if tipo == 'e':
				form = DelEgresoForm(instance = to_delete)
			elif tipo == 'i':
				form = DelIngresoForm(instance = to_delete)
			elif tipo == 'r':
				form = DelRenglonEgresoForm(instance = to_delete)
			elif tipo == 'p':
				form = DelTipoPagoForm(instance = to_delete)
			elif tipo == 't':
    				form = DelTransaccionesForm(instance = to_delete)
			elif tipo == 'c':
    				form = DelCorteForm(instance = to_delete)


	content = {'title_page':'Editar','form':form,'tipo':tipo,'mensajes':f'Borrara el registro con id {to_delete.id}','tmensaje':'alert-danger'}
	return render (request, 'finanzas/edit_tipo.html',content)


@login_required
def updateE(request,id):
    data = Egreso.objects.get(Usuario = request.user,id=id)
    if request.method == 'POST':
        form = EgresoForm(request.POST, instance=data)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/list/e/')
    else:
        form = EgresoForm(instance=data)

    context = {'username':request.user,'form':form}
    return render(request, 'finanzas/update.html', context)


@login_required
def updateI(request,id):
    data = Ingreso.objects.get(Usuario = request.user,id=id)
    if request.method == 'POST':
        form = IngresoForm(request.POST, instance=data)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/list/i/')
    else:
        form = IngresoForm(instance=data)

    context = {'username':request.user,'form':form}
    return render(request, 'finanzas/update.html', context)


@login_required
def updateR(request,id):
    data = RenglonEgreso.objects.get(Usuario = request.user,id=id)
    if request.method == 'POST':
        form = RenglonEgresoForm(request.POST, instance=data)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/list/r/')
    else:
        form = RenglonEgresoForm(instance=data)

    context = {'username':request.user,'form':form}
    return render(request, 'finanzas/update.html', context)

@login_required
def updateP(request,id):
    data = TipoPago.objects.get(Usuario = request.user,id=id)
    if request.method == 'POST':
        form = TipoPagoForm(request.POST, instance=data)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/list/ti/')
    else:
        form = TipoPagoForm(instance=data)

    context = {'username':request.user,'form':form}
    return render(request, 'finanzas/update.html', context)



def list(request,tipo):
    if tipo == 'p':
    	data = TipoPago.objects.filter(Usuario=request.user)
    	template='finanzas/list_ti.html'
    elif tipo == 'i':
    	data = Ingreso.objects.filter(Usuario=request.user)
    	template='finanzas/list_i.html'

    elif tipo == 'e':
        data = Egreso.objects.filter(Usuario=request.user)
        template='finanzas/list_e.html'	

    elif tipo == 'r':
        data = RenglonEgreso.objects.filter(Usuario=request.user)
        template='finanzas/list_r.html'		

    context = {'username':request,'data':data}
    return render(request, template, context)


def listCorte(request):
    data = Corte.objects.filter(Usuario=request.user, EstadoActivo=1).order_by('-id')
    template='finanzas/list_c.html'		
    context = {'username':request,'data':data}
    return render(request, template, context)


Meses = {'Ene':1,
         'Feb':2,
         'Mar':3,
         'Abr':4,
         'May':5,
         'Jun':6,
         'Jul':7,
         'Ago':8,
         'Sep':9,
         'Oct':10,
         'Nov':11,
         'Dec':12,}



def GenerarCorte (user,Ano,Mes):
    tingreso = 0
    tegreso = 0
    transacciones = []
    ingresos = Transacciones.objects.filter(Usuario=str(user),TipoTransaccion='I',EstadoActivo=1)
    egresos = Transacciones.objects.filter(Usuario=str(user),TipoTransaccion='E',EstadoActivo=1)
    for i in ingresos:
        if i.FechaTransaccion.month == Meses.get(Mes) and i.FechaTransaccion.year == int(Ano):
            tingreso = tingreso + int(i.Monto)
            transacciones.append(i.id)
    for e in egresos:
        if e.FechaTransaccion.month == Meses.get(Mes) and e.FechaTransaccion.year == int(Ano):
            tegreso = tegreso + int(e.Monto)
            transacciones.append(e.id)

    data = {'TotalIngresos':tingreso,'TotalEgresos':tegreso,'BalanceCorte':tingreso - tegreso,'transacciones':transacciones}
    return data



def GeneraCorte(request):
    BalanceInicial = Users.objects.get(username = request.user).limite
    if request.method == 'POST':
        form = GeneraCorteForm(request.POST)
        if form.is_valid():
            DatoCorte = GenerarCorte(request.user.id,request.POST['Ano'],request.POST['Mes'])
            #form.save()

proyectofinanzas/finanzas/templates/finanzas/add_transacciones.html
{% extends 'finanzas/base.html' %}
{% block content %}
{% load crispy_forms_tags %}
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Registrar Transaccion</h1>
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Transacciones</h6>
      </div>
      <div class="card-body">
        <div class="table-responsive">

    <form method="post">     {% csrf_token %}
    {{ form | crispy }}
    <button type="submit" class="btn btn-primary">Crear</button>


                </div>
            </form>  

  </div>


        </div>
      </div>
    </div>

  </div>
  <!-- /.container-fluid -->

</div>
<!-- End of Main Content -->







{% endblock %}

proyectofinanzas/finanzas/templates/finanzas/busqueda.html
{% extends 'finanzas/base.html' %}
{% block content %}



<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Detalles del Corte</h1>
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
      <div class="card-header py-3">
      <div class="card-body">
            <div class="col-md-8">
         <div class="tab-content profile-tab" id="myTabContent">
        <div class="table-responsive">
          <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
              <tr>
                <th>Resultado</th>
                <th>Accion</th>
              </tr>
            </thead>
            <tbody>

{% for data in items %}
              <tr>
                <td>{{data.Descripcion}}</td>
                <td>
                <a class="edit" title="Detalles" data-toggle="tooltip" href="/cortes/{{ data.id }}/"><i class="material-icons">dvr</i></a>                    </td>
{% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>

  </div>
  <!-- /.container-fluid -->

</div>
<!-- End of Main Content -->







{% endblock %}

proyectofinanzas/finanzas/templates/finanzas/edit_tipo.html
{% extends 'finanzas/base.html' %}
{% block content %}
<form class="forms-sample" method="POST"> {% csrf_token %}

<div class="alert {{tmensajes}}" role="alert">
  {{mensajes}}
</div>

    <div class="form-group">
           <label for="exampleInputName1">{{form.Descripcion.label}}</label>
                           {{ form.Descripcion }}
    </div>
    <div class="form-group">
        <label for="exampleInputName1">{{form.Tipo.label}}</label>
                        {{ form.Tipo }}
 </div>
    <div class="form-group">
           <label for="exampleInputName1">{{form.Activo.label}}</label>
                           {{ form.Activo }}
    </div>
      <input type="submit" class="btn btn-primary btn-fw" value="Submit" />
</form>
{% endblock %}

proyectofinanzas/finanzas/templates/finanzas/index.html
{% extends 'finanzas/base.html' %}
{% block content %}


{% endblock %}

proyectofinanzas/finanzas/templates/finanzas/list_c_gen.html
{% extends 'finanzas/base.html' %}
{% block content %}
{% load crispy_forms_tags %}
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Generar Cortes</h1>
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Cortes</h6>
      </div>
      <div class="card-body">
        <div class="table-responsive">

    <form method="post">     {% csrf_token %}
    {{ form | crispy }}

    <button type="submit" class="btn btn-primary">Crear</button>


                </div>
            </form>  

  </div>


        </div>
      </div>
    </div>

  </div>
  <!-- /.container-fluid -->

</div>
<!-- End of Main Content -->







{% endblock %}

proyectofinanzas/finanzas/templates/finanzas/profile.html
{% extends 'finanzas\base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<style>
   .emp-profile{
   padding: 3%;
   margin-top: 3%;
   margin-bottom: 3%;
   border-radius: 0.5rem;
   background: #fff;
   }
   .profile-img{
   text-align: center;
   }
   .profile-img img{
   width: 70%;
   height: 100%;
   }
   .profile-img .file {
   position: relative;
   overflow: hidden;
   margin-top: -20%;
   width: 70%;
   border: none;
   border-radius: 0;
   font-size: 15px;
   background: #212529b8;
   }
   .profile-img .file input {
   position: absolute;
   opacity: 0;
   right: 0;
   top: 0;
   }
   .profile-head h5{
   color: #333;
   }
   .profile-head h6{
   color: #0062cc;
   }
   .profile-edit-btn{
   border: none;
   border-radius: 1.5rem;
   width: 70%;
   padding: 2%;
   font-weight: 600;
   color: #6c757d;
   cursor: pointer;
   }
   .proile-rating{
   font-size: 12px;
   color: #818182;
   margin-top: 5%;
   }
   .proile-rating span{
   color: #495057;
   font-size: 15px;
   font-weight: 600;
   }
   .profile-head .nav-tabs{
   margin-bottom:5%;
   }
   .profile-head .nav-tabs .nav-link{
   font-weight:600;
   border: none;
   }
   .profile-head .nav-tabs .nav-link.active{
   border: none;
   border-bottom:2px solid #0062cc;
   }
   .profile-work{
   padding: 14%;
   margin-top: -15%;
   }
   .profile-work p{
   font-size: 12px;
   color: #818182;
   font-weight: 600;
   margin-top: 10%;
   }
   .profile-work a{
   text-decoration: none;
   color: #495057;
   font-weight: 600;
   font-size: 14px;
   }
   .profile-work ul{
   list-style: none;
   }
   .profile-tab label{
   font-weight: 600;
   }
   .profile-tab p{
   font-weight: 600;
   color: #0062cc;
   }
</style>
<div class="container emp-profile">
   <form method="post">
      {% csrf_token %}
      <div class="row">
         <div class="col-md-4">
            <div class="profile-img">
               <img src="https://banner2.kisspng.com/20180722/gfc/kisspng-user-profile-2018-in-sight-user-conference-expo-5b554c0968c377.0307553315323166814291.jpg" alt=""/>
            </div>
         </div>
         <div class="col-md-6">
            <div class="profile-head">
               <h5>
                  {{ username.get_full_name}}
               </h5>
               <h6>
                  {{username.position}} | {{username.company}}
               </h6>
               <p class="proile-rating">{{ username.birth_date}}</p>
               <ul class="nav nav-tabs" id="myTab" role="tablist">
                  <li class="nav-item">
                     <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">About</a>
                  </li>
               </ul>
            </div>
         </div>
         <div class="col-md-2">
<a href="{% url 'editprofile' %}" class="btn btn-info" role="button">Edit Profile</a>

   </div>
   </div>
   <div class="row">
      <div class="col-md-4">
         <div class="profile-work">
            <div class="colorlib-footer">
               <div class="d-flex justify-content-center">
                  <ul class="d-flex align-items-center">
                     <li class="d-flex align-items-center jusitfy-content-center"><a href="#"><i class="icon-facebook"></i></a></li>
                     <li class="d-flex align-items-center jusitfy-content-center"><a href="#"><i class="icon-twitter"></i></a></li>
                     <li class="d-flex align-items-center jusitfy-content-center"><a href="#"><i class="icon-instagram"></i></a></li>
                  </ul>
               </div>
            </div>
         </div>
      </div>
      <div class="col-md-8">
         <div class="tab-content profile-tab" id="myTabContent">
            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
               <div class="row">
                  <div class="col-md-6">
                     <label>Usuario</label>
                  </div>
                  <div class="col-md-6">
                     <p>{{username.username}}</p>
                  </div>
               </div>
               <div class="row">
                  <div class="col-md-6">
                     <label>Correo Electronico</label>
                  </div>
                  <div class="col-md-6">
                     <p>{{username.email}}</p>
                  </div>
               </div>
               <div class="row">
                  <div class="col-md-6">
                     <label>Limite</label>
                  </div>
                  <div class="col-md-6">
                     <p>{{username.limite}}</p>
                  </div>
               </div>
               <div class="row">
                  <div class="col-md-6">
                     <label>Tipo Persona</label>
                  </div>
                  <div class="col-md-6">
                     <p>{{username.get_tipoPersona_display}}</p>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
   </form>           
</div>
{% endblock %}

proyectofinanzas/finanzas/templates/finanzas/update.html
{% extends 'finanzas/base.html' %}
{% block content %}
{% load crispy_forms_tags %}
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Tipos</h1>
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Crear</h6>
      </div>
      <div class="card-body">
        <div class="table-responsive">

    <form method="post">     {% csrf_token %}
    {{ form | crispy }}

    <button type="submit" class="btn btn-primary">Crear</button>


                </div>
            </form>  

  </div>


        </div>
      </div>
    </div>

  </div>
  <!-- /.container-fluid -->

</div>
<!-- End of Main Content -->







{% endblock %}